(function (COM_AXES) {
    COM_AXES[COM_AXES["PRICE"] = 0] = "PRICE";
    COM_AXES[COM_AXES["CONFORT"] = 1] = "CONFORT";
    COM_AXES[COM_AXES["RESISTANCE"] = 2] = "RESISTANCE";
    COM_AXES[COM_AXES["ESTHETIC"] = 3] = "ESTHETIC";
})(exports.COM_AXES || (exports.COM_AXES = {}));
var COM_AXES = exports.COM_AXES;
(function (IMPROVEMENT_TYPE) {
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["NONE"] = 0] = "NONE";
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["MINOR"] = 1] = "MINOR";
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["MAJOR"] = 2] = "MAJOR";
})(exports.IMPROVEMENT_TYPE || (exports.IMPROVEMENT_TYPE = {}));
var IMPROVEMENT_TYPE = exports.IMPROVEMENT_TYPE;
(function (STAR_RATINGS) {
    STAR_RATINGS[STAR_RATINGS["ONE_STAR"] = 1] = "ONE_STAR";
    STAR_RATINGS[STAR_RATINGS["TWO_STAR"] = 2] = "TWO_STAR";
    STAR_RATINGS[STAR_RATINGS["THREE_STAR"] = 3] = "THREE_STAR";
    STAR_RATINGS[STAR_RATINGS["FOUR_STAR"] = 4] = "FOUR_STAR";
    STAR_RATINGS[STAR_RATINGS["FIVE_STAR"] = 5] = "FIVE_STAR";
})(exports.STAR_RATINGS || (exports.STAR_RATINGS = {}));
var STAR_RATINGS = exports.STAR_RATINGS;
(function (PERIODS) {
    PERIODS[PERIODS["QUARTER"] = 3] = "QUARTER";
    PERIODS[PERIODS["HALF_YEAR"] = 6] = "HALF_YEAR";
    PERIODS[PERIODS["YEAR"] = 12] = "YEAR";
})(exports.PERIODS || (exports.PERIODS = {}));
var PERIODS = exports.PERIODS;
//# sourceMappingURL=ENUMS.js.map